# Generated by Django 5.0.7 on 2024-07-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="picture",
        ),
    ]
