# Generated by Django 5.0.7 on 2024-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="imagen",
            field=models.ImageField(null=True, upload_to="cocktails/"),
        ),
    ]
